version: "2.1"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    links:
      - pg
      - rmq
    depends_on:
      pg:
        condition: service_healthy
      rmq:
        condition: service_healthy
    environment:
      - DEBUG=false
      - SECRET_KEY=django-insecure-339&eig$$uv6*6sfhnw_h9a*0@*$$4^o76w$$ip#x&k(sjs!0@$$&_

      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - POSTGRES_DB=larek_db
      - POSTGRES_USER=larek_user
      - POSTGRES_PASSWORD=larek_password

      - RMQ_URL=amqp://larek_rmq:larek_password@rmq:5672/
    command: bash -c "python manage.py migrate && celery -A larek worker -l info --detach && python manage.py runserver 0.0.0.0:8000"
    volumes:
     - .:/app/

  pg:
    image: postgres:12
    environment:
      - POSTGRES_DB=larek_db
      - POSTGRES_USER=larek_user
      - POSTGRES_PASSWORD=larek_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U larek_user -d larek_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=larek_rmq
      - RABBITMQ_DEFAULT_PASS=larek_password
    ports:
      - "35672:15672"
      - "25672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
